App\Models\Account:
    type: entity
    table: account
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        lastname:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        firstname:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        postalcode:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        civility:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        login:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        country:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
    lifecycleCallbacks: {  }
