App\Models\Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        price:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        format:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        imagesource:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
